name: Release

on:
  pull_request:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - id: git_checkout
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: setup_go
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'
          cache-dependency-path: |
             ./go.sum
      - id: run_goreleaser
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
